namespace ZRISK;

using {managed} from '@sap/cds/common';

entity FLATFILE : managed {

    key DCSID : String(20)
    @title: 'DCS ID';
    key MIC : String(4)
    @title: 'MIC';
    key PRICETYPE : String(2)
    @title: 'Price Type';
    key MKEYDT : Date
    @title: 'Maturity Keydate';
    key PRICEDATE : Date
    @title: 'Price Date';
    PRICE : Decimal(20,8)
    @title: 'Price';
    PER : Integer
    @title: 'Per';
    UOM : String(3)
    @title: 'Unit Of Measure';
    CURRENCY : String(5)
    @title: 'Currency';
    FILENAME : String(100)
    @title: 'File name';

}

entity JOBSUMM : managed {
    @Core.Computed
    @sql.append: 'GENERATED BY DEFAULT AS IDENTITY'
    key JOB_ID : Integer
    @title: 'Job ID';
    FORCORR       : String(10)
    @title: 'Values - For or Corr';
    MODEL         : String(10)
    @title: 'XGBoost, ARIMA';
    SRCDCSID      : String(20)
    @title: 'Source DCSID';
    SRCMIC        : String(4)
    @title: 'Source MIC';
    TARDCSID      : String(20)
    @title: 'Target DCSID';
    TARMIC        : String(4)
    @title: 'Target MIC';
    HORTY         : String(1)
    @title: 'Horizon type(Values - D,W,M)';
    HORVAL        : Integer
    @title: 'Horizon Value';
    JOBSTARTDATE  : Date
    @title: 'Job Start Date';
    JOBSTTMSTMP   : Timestamp
    @title: 'Job Start Time Stamp';
    JOBENDTMSTMP  : Timestamp
    @title: 'Job End Time Stamp';
    JOBSTATUS : String(10) not null default 'ENTERED'
    @title: 'Job Status'
    @assert.range: [
        'ENTERED',
        'RUNNING',
        'COMPLETED'
    ];
    JOBCOMPPCT    : Integer
    @title: 'Job Completion Percentage';
}